In [1]:
import numpy as np
import pandas as pd

In [2]:
ipl = pd.read_csv('ipl.csv')

## Attributes of DataFrame

#### size <hr>

In [3]:
ipl.size

32318

#### dtypes<hr>

In [4]:
ipl.dtypes

date                 str
season               str
city                 str
venue                str
team1                str
team2                str
toss_winner          str
toss_decision        str
team1_runs         int64
team1_wickets      int64
team2_runs         int64
team2_wickets      int64
winner               str
result_type          str
win_by_runs        int64
win_by_wickets     int64
player_of_match      str
match_referee        str
umpire1              str
umpire2              str
tv_umpire            str
reserve_umpire       str
overs_limit        int64
team1_players        str
team2_players        str
year               int64
dtype: object

#### shape<hr>

In [5]:
ipl.shape

(1243, 26)

#### values<hr>

In [6]:
ipl.values

array([['2008-04-18', '2007/08', 'Bangalore', ...,
        'R Dravid, W Jaffer, V Kohli, JH Kallis, CL White, MV Boucher, B Akhil, AA Noffke, P Kumar, Z Khan, SB Joshi',
        'SC Ganguly, BB McCullum, RT Ponting, DJ Hussey, Mohammad Hafeez, LR Shukla, WP Saha, AB Agarkar, AB Dinda, M Kartik, I Sharma',
        2008],
       ['2008-04-19', '2007/08', 'Chandigarh', ...,
        'K Goel, JR Hopes, KC Sangakkara, Yuvraj Singh, SM Katich, IK Pathan, P Dharmani, B Lee, PP Chawla, WA Mota, S Sreesanth',
        'PA Patel, ML Hayden, MEK Hussey, MS Dhoni, SK Raina, JDP Oram, S Badrinath, Joginder Sharma, P Amarnath, MS Gony, M Muralitharan',
        2008],
       ['2008-04-19', '2007/08', 'Delhi', ...,
        'G Gambhir, V Sehwag, S Dhawan, MK Tiwary, KD Karthik, R Bhatia, M Manhas, DL Vettori, MF Maharoof, B Geeves, GD McGrath',
        'T Kohli, YK Pathan, SR Watson, M Kaif, DS Lehmann, RA Jadeja, M Rawat, D Salunkhe, SK Warne, SK Trivedi, MM Patel',
        2008],
       ...,
       ['2026-05-27', '2026', 'New Chandigarh', ...,
        'YBK Jaiswal, V Suryavanshi, Dhruv Jurel, R Parag, D Ferreira, MD Shanaka, RA Jadeja, JC Archer, N Burger, SS Mishra, Brijesh Sharma, Yash Raj Punja',
        'PP Hinge, Abhishek Sharma, TM Head, Ishan Kishan, R Smaran, H Klaasen, Nithish Kumar Reddy, Salil Arora, PJ Cummins, Shivang Kumar, E Malinga, Sakib Hussain',
        2026],
       ['2026-05-29', '2026', 'New Chandigarh', ...,
        'TU Deshpande, YBK Jaiswal, V Suryavanshi, Dhruv Jurel, RA Jadeja, R Parag, MD Shanaka, JC Archer, D Ferreira, N Burger, Brijesh Sharma, Yash Raj Punja',
        'Mohammed Siraj, B Sai Sudharsan, Shubman Gill, JC Buttler, Washington Sundar, R Tewatia, JO Holder, N Sindhu, Rashid Khan, R Sai Kishore, K Rabada, M Prasidh Krishna',
        2026],
       ['2026-05-31', '2026', 'Ahmedabad', ...,
        'M Prasidh Krishna, B Sai Sudharsan, Shubman Gill, N Sindhu, JC Buttler, Washington Sundar, Arshad Khan, R Tewatia, JO Holder, Rashid Khan, K Rabada, Mohammed Siraj',
        'JA Duffy, VR Iyer, V Kohli, D Padikkal, RM Patidar, KH Pandya, TH David, JM Sharma, R Shepherd, B Kumar, JR Hazlewood, Rasikh Salam',
        2026]], shape=(1243, 26), dtype=object)

#### index<hr>

In [7]:
ipl.index

RangeIndex(start=0, stop=1243, step=1)

In [31]:
a = pd.DataFrame({'math': [90,70,80,88],
                  'english':[56,70,86,45]})
a.index = ['Harsh', 'Rasika', 'Jay', 'Viraj']
a.index = ['Nikita', 'Rasika Hajare', 'Peter', 'Ritanshu']
x = list(a.index)
x[0] = 'Nikita Nikam'
a.index = x
a

               math  english
Nikita Nikam     90       56
Rasika Hajare    70       70
Peter            80       86
Ritanshu         88       45

#### columns <hr>

In [9]:
ipl.columns

Index(['date', 'season', 'city', 'venue', 'team1', 'team2', 'toss_winner',
       'toss_decision', 'team1_runs', 'team1_wickets', 'team2_runs',
       'team2_wickets', 'winner', 'result_type', 'win_by_runs',
       'win_by_wickets', 'player_of_match', 'match_referee', 'umpire1',
       'umpire2', 'tv_umpire', 'reserve_umpire', 'overs_limit',
       'team1_players', 'team2_players', 'year'],
      dtype='str')

In [32]:
a.columns = ['English', 'History']
a

               English  History
Nikita Nikam        90       56
Rasika Hajare       70       70
Peter               80       86
Ritanshu            88       45

In [11]:
movies = pd.read_csv('bollywood.csv')

## Methods of DataFrame

#### head <hr>

In [12]:
movies.head() # first 5 rows
ipl.head(3)

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players,year
0,2008-04-18,2007/08,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,82,10,...,BB McCullum,J Srinath,Asad Rauf,RE Koertzen,AM Saheba,VN Kulkarni,20,"R Dravid, W Jaffer, V Kohli, JH Kallis, CL Whi...","SC Ganguly, BB McCullum, RT Ponting, DJ Hussey...",2008
1,2008-04-19,2007/08,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,207,4,...,MEK Hussey,S Venkataraghavan,MR Benson,SL Shastri,RB Tiffin,MSS Ranawat,20,"K Goel, JR Hopes, KC Sangakkara, Yuvraj Singh,...","PA Patel, ML Hayden, MEK Hussey, MS Dhoni, SK ...",2008
2,2008-04-19,2007/08,Delhi,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,132,1,...,MF Maharoof,GR Viswanath,Aleem Dar,GA Pratapkumar,IL Howell,Unknown,20,"G Gambhir, V Sehwag, S Dhawan, MK Tiwary, KD K...","T Kohli, YK Pathan, SR Watson, M Kaif, DS Lehm...",2008

#### tail<hr>

In [13]:
ipl.tail() #last 5 rows
movies.tail(7)

                         movie              lead
1493  Devdas (2002 Hindi film)    Shah Rukh Khan
1494                    Kaante  Amitabh Bachchan
1495    Hum Tumhare Hain Sanam    Shah Rukh Khan
1496       Aankhen (2002 film)  Amitabh Bachchan
1497           Saathiya (film)      Vivek Oberoi
1498            Company (film)        Ajay Devgn
1499      Awara Paagal Deewana      Akshay Kumar

#### sample<hr>

In [14]:
ipl.sample() # a random row
ipl.sample(3) # 3 random row

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players,year
622,2017-05-07,2017,Chandigarh,"Punjab Cricket Association IS Bindra Stadium, ...",Kings XI Punjab,Gujarat Lions,Gujarat Lions,field,189,3,...,DR Smith,J Srinath,A Nand Kishore,VK Sharma,S Ravi,Navdeep Singh,20,"MJ Guptill, HM Amla, SE Marsh, GJ Maxwell, AR ...","DR Smith, Ishan Kishan, SK Raina, KD Karthik, ...",2017
41,2008-05-18,2007/08,Kolkata,Eden Gardens,Kolkata Knight Riders,Chennai Super Kings,Kolkata Knight Riders,bat,149,5,...,M Ntini,FM Engineer,Asad Rauf,K Hariharan,AM Saheba,S Banerjee,20,"Salman Butt, Mohammad Hafeez, SC Ganguly, DB D...","PA Patel, SP Fleming, S Vidyut, SK Raina, S Ba...",2008
396,2013-05-24,2013,Kolkata,Eden Gardens,Mumbai Indians,Rajasthan Royals,Rajasthan Royals,bat,169,6,...,Harbhajan Singh,RS Madugalle,C Shamshuddin,SJA Taufel,HDPK Dharmasena,K Srinath,20,"DR Smith, AP Tare, KD Karthik, RG Sharma, KA P...","R Dravid, AM Rahane, SR Watson, SV Samson, STR...",2013

#### set_index<hr>
`syntax : variable.set_index(column_name)`

In [15]:
japan  = pd.read_csv('japan_birth_statistics_1899_2023.csv')
japan.set_index('year')  # this will not change the original df

,total_births,male_births,female_births,crude_birth_rate,sex_ratio_at_birth,total_fertility_rate
year,,,,,,
2023,727288,372603,354685,6.0,105.1,1.20
2022,770759,395257,375502,6.3,105.3,1.26
2021,811622,415903,395719,6.6,105.1,1.30
2020,840835,430713,410122,6.8,105.0,1.33
2019,865239,443430,421809,7.0,105.1,1.36
...,...,...,...,...,...,...
1903,1489816,763806,726010,32.7,105.2,NaN
1902,1510835,773296,737539,33.6,104.8,NaN
1901,1501591,769494,732097,33.9,105.1,NaN
1900,1420534,727916,692618,32.4,105.1,NaN
1899,1386981,713442,673539,32.0,105.9,NaN

In [16]:
japan.head(1)

,year,total_births,male_births,female_births,crude_birth_rate,sex_ratio_at_birth,total_fertility_rate
0,2023,727288,372603,354685,6.0,105.1,1.2

`syntax : variable.set_index(column_name, inplace = True)`

In [17]:
japan.set_index('year',inplace=True)

In [18]:
japan.head(1)

,total_births,male_births,female_births,crude_birth_rate,sex_ratio_at_birth,total_fertility_rate
year,,,,,,
2023,727288,372603,354685,6.0,105.1,1.2

#### drop<hr>
`syntax : variable.drop( row/column , axis )`

In [35]:
a.drop('English', axis=1)
# a.drop('English', axis=1, inplace=True) # this will modify the original

               History
Nikita Nikam        56
Rasika Hajare       70
Peter               86
Ritanshu            45

In [30]:
a.drop('Peter', axis=0)
# a.drop('harsh', axis=0) # Error because harsh is not present

               math  english
Nikita Nikam     90       56
Rasika Hajare    70       70
Ritanshu         88       45

In [27]:
a

               History
Nikita Nikam        56
Rasika Hajare       70
Peter               86
Ritanshu            45

#### info<hr>

In [41]:
ipl.info()

<class 'pandas.DataFrame'>
RangeIndex: 1243 entries, 0 to 1242
Data columns (total 26 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   date             1243 non-null   str
 1   season           1243 non-null   str
 2   city             1243 non-null   str
 3   venue            1243 non-null   str
 4   team1            1243 non-null   str
 5   team2            1243 non-null   str
 6   toss_winner      1243 non-null   str
 7   toss_decision    1243 non-null   str
 8   team1_runs       1243 non-null   int64
 9   team1_wickets    1243 non-null   int64
 10  team2_runs       1243 non-null   int64
 11  team2_wickets    1243 non-null   int64
 12  winner           1218 non-null   str
 13  result_type      1243 non-null   str
 14  win_by_runs      1243 non-null   int64
 15  win_by_wickets   1243 non-null   int64
 16  player_of_match  1234 non-null   str
 17  match_referee    1243 non-null   str
 18  umpire1          1243 non-null   str
 19  umpire2          1243 non-null   str
 20  tv_umpire        1243 non-null   str
 21  reserve_umpire   1243 non-null   str
 22  overs_limit      1243 non-null   int64
 23  team1_players    1243 non-null   str
 24  team2_players    1243 non-null   str
 25  year             1243 non-null   int64
dtypes: int64(8), str(18)
memory usage: 252.6 KB

#### describe<hr>

In [46]:
ipl.describe()

,team1_runs,team1_wickets,team2_runs,team2_wickets,win_by_runs,win_by_wickets,overs_limit,year
count,1243.000000,1243.000000,1243.000000,1243.000000,1243.000000,1243.000000,1243.0,1243.000000
mean,165.851167,5.956557,157.349155,5.873693,13.932422,3.276750,20.0,2017.242156
std,35.490847,2.309341,34.613073,2.646538,23.861556,3.358216,0.0,5.550682
min,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,20.0,2008.000000
25%,144.000000,4.000000,138.000000,4.000000,0.000000,0.000000,20.0,2012.000000
50%,165.000000,6.000000,160.000000,6.000000,0.000000,3.000000,20.0,2017.000000
75%,189.000000,8.000000,179.000000,8.000000,20.000000,6.000000,20.0,2022.000000
max,287.000000,10.000000,265.000000,12.000000,146.000000,10.000000,20.0,2026.000000

In [50]:
ipl[['team1', 'team2']].describe()

                      team1           team2
count                  1243            1243
unique                   19              19
top     Chennai Super Kings  Mumbai Indians
freq                    142             152

#### sum<hr>

In [54]:
a.sum()
a.sum(axis=1)

Nikita Nikam     146
Rasika Hajare    140
Peter            166
Ritanshu         133
dtype: int64

In [55]:
ipl.sum()

date               2008-04-182008-04-192008-04-192008-04-202008-0...
season             2007/082007/082007/082007/082007/082007/082007...
city               BangaloreChandigarhDelhiKolkataMumbaiJaipurHyd...
venue              M Chinnaswamy StadiumPunjab Cricket Associatio...
team1              Royal Challengers BangaloreKings XI PunjabDelh...
team2              Kolkata Knight RidersChennai Super KingsRajast...
toss_winner        Royal Challengers BangaloreChennai Super Kings...
toss_decision      fieldbatbatbatbatbatbatfieldfieldfieldbatfield...
team1_runs                                                    206153
team1_wickets                                                   7404
team2_runs                                                    195585
team2_wickets                                                   7301
winner             Kolkata Knight RidersChennai Super KingsDelhi ...
result_type        completecompletecompletecompletecompletecomple...
win_by_runs                                                    17318
win_by_wickets                                                  4073
player_of_match    BB McCullumMEK HusseyMF MaharoofDJ HusseyMV Bo...
match_referee      J SrinathS VenkataraghavanGR ViswanathFM Engin...
umpire1            Asad RaufMR BensonAleem DarBF BowdenSJ DavisAl...
umpire2            RE KoertzenSL ShastriGA PratapkumarK Hariharan...
tv_umpire          AM SahebaRB TiffinIL HowellAsad RaufAV Jayapra...
reserve_umpire     VN KulkarniMSS RanawatUnknownF GomesSN Bandeka...
overs_limit                                                    24860
team1_players      R Dravid, W Jaffer, V Kohli, JH Kallis, CL Whi...
team2_players      SC Ganguly, BB McCullum, RT Ponting, DJ Hussey...
year                                                         2507432
dtype: object

#### isnull <hr>

In [ ]:
ipl.isnull()
ipl.isnull().sum()

date                0
season              0
city                0
venue               0
team1               0
team2               0
toss_winner         0
toss_decision       0
team1_runs          0
team1_wickets       0
team2_runs          0
team2_wickets       0
winner             25
result_type         0
win_by_runs         0
win_by_wickets      0
player_of_match     9
match_referee       0
umpire1             0
umpire2             0
tv_umpire           0
reserve_umpire      0
overs_limit         0
team1_players       0
team2_players       0
year                0
dtype: int64

In [81]:
demo1 = pd.DataFrame([[1,2,3],[np.nan,10],[10,20]])
demo1.isnull()

       0      1      2
0  False  False  False
1   True  False   True
2  False  False   True

#### notnull<hr>

In [58]:
ipl.notnull()

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players,year
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1238,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1239,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1240,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1241,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1242,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [82]:
demo1.notnull()

       0     1      2
0   True  True   True
1  False  True  False
2   True  True  False

#### duplicated <hr>

In [60]:
ipl.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
1238    False
1239    False
1240    False
1241    False
1242    False
Length: 1243, dtype: bool

In [66]:
demo = pd.DataFrame({'maths':[90,90,45,87], 'english':[80, 80,60, 70]})
demo.duplicated()

0    False
1     True
2    False
3    False
dtype: bool

#### drop_duplicate <hr>

In [69]:
demo.drop_duplicates()

   maths  english
0     90       80
2     45       60
3     87       70

In [72]:
demo.drop_duplicates(inplace=True)
demo

   maths  english
0     90       80
2     45       60
3     87       70

#### sort_values <hr>

In [76]:
demo.sort_values('english')

   maths  english
2     45       60
3     87       70
0     90       80