# DataFrame <hr>
A Pandas DataFrame is a two-dimensional, tabular data structure in Python that organizes data into rows and columns.
* It's a collection of rows and columns 
* we can also say it's a collection of Pandas Series

In [1]:
import pandas as pd

`syntax :- pd.DataFrame(collection)`

In [2]:
pd.DataFrame([[1,2,34,5],
              [1,'hello',45,6],
              [1,23,4,5]])

   0      1   2  3
0  1      2  34  5
1  1  hello  45  6
2  1     23   4  5

**DF with Tuple**
<hr>

In [5]:
pd.DataFrame(((23,45), (14,5)))

    0   1
0  23  45
1  14   5

**DF with set**
<hr>

In [6]:
pd.DataFrame({(2,1),(2,2),(4,5)})

   0  1
0  4  5
1  2  1
2  2  2

**DF with dict**
<hr>

In [18]:
marks = {'eng':[30,40,34,45],
         'maths':[50,0, 45, 32],
         'science':[30,40,25,46]}

pd.DataFrame(marks)

   eng  maths  science
0   30     50       30
1   40      0       40
2   34     45       25
3   45     32       46

When initializing a DataFrame with and unequal lengths element, Pandas automatically fill the missing values with NaN.

In [7]:
pd.DataFrame([[1,2],
              [2,3,4],
              [3,2]])

   0  1    2
0  1  2  NaN
1  2  3  4.0
2  3  2  NaN

When creating a DataFrame, the length of the index must match the total number of rows, and the length of the columns list must match the number of columns in the data.

In [8]:
pd.DataFrame([[1,2,2,34],
              [2,3,4,123],
              [3,2,23]],
            index=['first row', 'second row', 'third row'],
            columns=['1st', '2nd', '3rd', '4th'])

            1st  2nd  3rd    4th
first row     1    2    2   34.0
second row    2    3    4  123.0
third row     3    2   23    NaN