In [1]:
import numpy as np
import pandas as pd

# DataFrame<hr> 
- A pandas DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns). It is the primary data structure in the pandas library

1)  Creating the `DataFrame` using list

In [ ]:
l = [[100,90,'20'],
     [80,50,'3'],
     [120,80,'30',]]

df  = pd.DataFrame(l)
df

     0   1   2
0  100  90  20
1   80  50   3
2  120  80  30

2. Creating the `DataFrame` using dictionary

In [9]:
# using dicts

student_dict = {
    'name':['nitish','ankit','rupesh','rishabh','amit','ankita'],
    'iq':[100,90,120,80,0,0],
    'marks':[80,70,100,50,0,0],
    'package':[10,7,14,2,0,0]
}

students = pd.DataFrame(student_dict)
students

      name   iq  marks  package
0   nitish  100     80       10
1    ankit   90     70        7
2   rupesh  120    100       14
3  rishabh   80     50        2
4     amit    0      0        0
5   ankita    0      0        0

+ if we want to make a column as an index then we will use `DataFrame.set_index('column_name', inplace= True)`

In [11]:
students.set_index('name',inplace=True)
students

          iq  marks  package
name
nitish   100     80       10
ankit     90     70        7
rupesh   120    100       14
rishabh   80     50        2
amit       0      0        0
ankita     0      0        0