In [3]:
import numpy as np
import pandas as pd

# DataFrame<hr> 
- A pandas DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns). It is the primary data structure in the pandas library

1)  Creating the `DataFrame` using list

In [13]:
l = [[100,90,'20'],
     [80,50,'345'],
     [80,50,'344'],
     [80,50,'4465'],
     [120,80,'30',]]

df  = pd.DataFrame(l,index=[1,2,3,4,5],columns=['math', 'science', 'CS'])
df.index = {1:2, 3:4, 5:6, 7:8, 9:0}
df.columns = ['math', 'CS', 'IT']
df

   math  CS    IT
1   100  90    20
3    80  50   345
5    80  50   344
7    80  50  4465
9   120  80    30

2. Creating the `DataFrame` using dictionary

In [22]:
# using dicts

student_dict = {
    'name':['nitish','ankit','rupesh','rishabh','amit','ankita'],
    'iq':[100,90,120,80,0,0],
    'marks':[80,70,100,50,0,0],
    'package':[10,7,14,2,0,0]
}

students = pd.DataFrame(student_dict)
students

      name   iq  marks  package
0   nitish  100     80       10
1    ankit   90     70        7
2   rupesh  120    100       14
3  rishabh   80     50        2
4     amit    0      0        0
5   ankita    0      0        0

+ if we want to make a column as an index then we will use `DataFrame.set_index('column_name', inplace= True)`

In [ ]:
students.set_index('name',inplace=True)
students

          iq  marks  package
name
nitish   100     80       10
ankit     90     70        7
rupesh   120    100       14
rishabh   80     50        2
amit       0      0        0
ankita     0      0        0

In [31]:
df = pd.read_csv('data\Iris.csv')

<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
<>:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
C:\Users\LENOVO\AppData\Local\Temp\ipykernel_16860\2638558962.py:1: SyntaxWarning: "\I" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\I"? A raw string is also an option.
  df = pd.read_csv('data\Iris.csv')

In [ ]:
students['iq']
students[['iq', 'marks']]

          iq  marks
name
nitish   100     80
ankit     90     70
rupesh   120    100
rishabh   80     50
amit       0      0
ankita     0      0

In [47]:
df.set_index('Species', inplace= True)
df

                SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Species
Iris-setosa               5.1           3.5            1.4           0.2
Iris-setosa               4.9           3.0            1.4           0.2
Iris-setosa               4.7           3.2            1.3           0.2
Iris-setosa               4.6           3.1            1.5           0.2
Iris-setosa               5.0           3.6            1.4           0.2
...                       ...           ...            ...           ...
Iris-virginica            6.7           3.0            5.2           2.3
Iris-virginica            6.3           2.5            5.0           1.9
Iris-virginica            6.5           3.0            5.2           2.0
Iris-virginica            6.2           3.4            5.4           2.3
Iris-virginica            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [48]:
df[['SepalLengthCm','SepalWidthCm']]

                SepalLengthCm  SepalWidthCm
Species
Iris-setosa               5.1           3.5
Iris-setosa               4.9           3.0
Iris-setosa               4.7           3.2
Iris-setosa               4.6           3.1
Iris-setosa               5.0           3.6
...                       ...           ...
Iris-virginica            6.7           3.0
Iris-virginica            6.3           2.5
Iris-virginica            6.5           3.0
Iris-virginica            6.2           3.4
Iris-virginica            5.9           3.0

[150 rows x 2 columns]

In [51]:
df[1:12]
students[::]
students['nitish':'rupesh']
df['Iris-setosa':'Iris-virginica']

                SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
Species
Iris-setosa               5.1           3.5            1.4           0.2
Iris-setosa               4.9           3.0            1.4           0.2
Iris-setosa               4.7           3.2            1.3           0.2
Iris-setosa               4.6           3.1            1.5           0.2
Iris-setosa               5.0           3.6            1.4           0.2
...                       ...           ...            ...           ...
Iris-virginica            6.7           3.0            5.2           2.3
Iris-virginica            6.3           2.5            5.0           1.9
Iris-virginica            6.5           3.0            5.2           2.0
Iris-virginica            6.2           3.4            5.4           2.3
Iris-virginica            5.9           3.0            5.1           1.8

[150 rows x 4 columns]

In [52]:
df[['SepalLengthCm','SepalWidthCm']][1:3]

             SepalLengthCm  SepalWidthCm
Species
Iris-setosa            4.9           3.0
Iris-setosa            4.7           3.2