In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('titanic.csv')
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    str
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    str
 11  Embarked     888 non-null    str
dtypes: float64(2), int64(4), str(6)
memory usage: 83.7 KB

In [4]:
df.set_index('PassengerId', inplace=True)

In [5]:
df.head(1)

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3rd,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

## What is Data Cleaning? <hr>
Data cleaning is the process of identifying and correcting (or removing) errors, inconsistencies, and inaccuracies in a dataset to improve its quality and reliability.

It involves transforming raw, messy data into a clean, structured format that's ready for analysis, visualization, or machine learning.

**The 6 Steps of Data Cleaning**

#### **1. Renaming the Columns**<hr>
* Changing column names to make them more descriptive, consistent, and easier to understand.

* A clear column names help anyone reading the dataset understand what each variable represents without confusion. 
    
* It also makes coding easier and reduces errors when referring to columns in analysis.

In [8]:
# In order to perform the data cleaning i will use Titanic Data set in this data set three col name are not very clear sibsp, parch, fare
rename = {'SibSp':'Sibling/Spouse',
          'Parch': 'Parent/Child',
          'Fare':'Ticket_fare'}

df.rename(columns=rename, inplace=True)
df.head(1)

,Survived,Pclass,Name,Sex,Age,Sibling/Spouse,Parent/Child,Ticket,Ticket_fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3rd,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.25,NaN,S

#### **2. Removing Duplicate Rows**<hr>
* Identifying and deleting identical rows that appear multiple times in your dataset.

* Duplicate entries can artificially inflate your data, leading to incorrect analysis results and biased insights. Removing them ensures each observation is counted only once.

`since there is no Dupicated data we are not removing anything`

In [16]:
df.duplicated().sum()
df.drop_duplicates(inplace=True)

In [19]:
df.duplicated(subset=['Ticket','Name']).sum()
df.drop_duplicates(subset=['Ticket','Name'], inplace=True)

#### **3. Changing the Data Present in a Particular Column**<hr>
*  Standardizing inconsistent values within a column (like "First", "1st", "FIRST" all becoming "1st") or correcting incorrect entries.

* Inconsistent categorical data can break analysis and cause errors in grouping, filtering, and visualization. Uniform values ensure accurate aggregation and comparison.

syntax to chage values in a column : 
```
    d = {old_value : new_value, ....}
    df[COLUMN] = df[COLUMN].map( d )
```

If we want to change one value we need to mention all the unique value.

In [27]:
df['Pclass'].unique()

<StringArray>
['3rd', '1', '2', '3', '1st']
Length: 5, dtype: str

In [28]:
change_values = {'1':'1st',
                 '2':'2nd',
                 '3':'3rd',
                 '3rd':'3rd',
                 '1st':'1st'}
df['Pclass'] = df['Pclass'].map(change_values)

In [50]:
df.sample(2)

,Survived,Pclass,Name,Sex,Age,Sibling/Spouse,Parent/Child,Ticket,Ticket_fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
102,0,3rd,"Petroff, Mr. Pastcho (""Pentcho"")",male,NaN,0,0,349215,7.8958,NaN,S
262,1,3rd,"Asplund, Master. Edvin Rojj Felix",male,3.0,4,2,347077,31.3875,NaN,S

#### **4. Handling NaN Values**<hr>
* Dealing with missing data points (Not a Number, None, or null values) by either removing rows with missing data or filling them with appropriate substitute values.

* Many algorithms (Data analysis or Data science algorithms) cannot process missing values, and they can skew statistical analysis. 

* The choice between dropping or filling depends on how much data is missing and its importance to your analysis.

In [ ]:
# we can handle the nan in embarked column

df['Embarked'].isnull().sum() # since there is only 3 null/nan/None values we can remove it.

df.dropna(subset=['Embarked'], inplace=True)

In [63]:
df['Embarked'].isnull().sum()

np.int64(0)

In [68]:
# we can handle the nan in age column
df['Age'].isnull().sum()

age_median = df['Age'].median()
df['Age'] = df['Age'].fillna(age_median)

In [73]:
df['Age'] = df.Age.astype('int32')
df.Age

PassengerId
1      22
2      38
3      26
4      35
5      35
       ..
887    27
888    19
889    28
890    26
891    32
Name: Age, Length: 888, dtype: int32

#### **5. Dropping Unwanted Columns**<hr>
* Removing entire columns that are irrelevant, redundant, or contain too much missing information to be useful.

* Extra unnecessary columns add noise, increase data size, and slow down processing.

* Focusing on relevant features improves model performance and makes analysis more efficient.

In [75]:
df.drop(columns=['Cabin'], inplace=True)

In [76]:
df.head(1)

,Survived,Pclass,Name,Sex,Age,Sibling/Spouse,Parent/Child,Ticket,Ticket_fare,Embarked
PassengerId,,,,,,,,,,
1,0,3rd,"Braund, Mr. Owen Harris",male,22,1,0,A/5 21171,7.25,S

#### **6. Dropping Unwanted Rows**<hr>
* Removing specific rows from the dataset that contain outliers, errors, or irrelevant observations.

* Outliers or erroneous entries can distort statistical measures and negatively impact model training. 

* Removing them ensures your analysis is based on accurate, representative data.

In [80]:
df.drop(index=[887], inplace=True)

<hr>extra data cleaning methods <hr>

In [94]:
df1 = pd.DataFrame([[1],
                    [2,4],
                    [3,],
                    [4,5],
                    [5,],
                    [6,],
                    [7,10]])
df1

   0     1
0  1   NaN
1  2   4.0
2  3   NaN
3  4   5.0
4  5   NaN
5  6   NaN
6  7  10.0

In [95]:
df1[1].ffill()

0     NaN
1     4.0
2     4.0
3     5.0
4     5.0
5     5.0
6    10.0
Name: 1, dtype: float64

In [96]:
df1[1].bfill()

0     4.0
1     4.0
2     5.0
3     5.0
4    10.0
5    10.0
6    10.0
Name: 1, dtype: float64

In [97]:
# df1[1].fillna(method = 'ffill') #depricated only works in version 2