In [3]:
import numpy as np
import pandas as pd

### read_csv
`syntax : pd.read_csv(path)`

In [4]:
japan = pd.read_csv('japan_birth_statistics_1899_2023.csv')
japan

,year,total_births,male_births,female_births,crude_birth_rate,sex_ratio_at_birth,total_fertility_rate
0,2023,727288,372603,354685,6.0,105.1,1.20
1,2022,770759,395257,375502,6.3,105.3,1.26
2,2021,811622,415903,395719,6.6,105.1,1.30
3,2020,840835,430713,410122,6.8,105.0,1.33
4,2019,865239,443430,421809,7.0,105.1,1.36
...,...,...,...,...,...,...,...
117,1903,1489816,763806,726010,32.7,105.2,NaN
118,1902,1510835,773296,737539,33.6,104.8,NaN
119,1901,1501591,769494,732097,33.9,105.1,NaN
120,1900,1420534,727916,692618,32.4,105.1,NaN
121,1899,1386981,713442,673539,32.0,105.9,NaN

In [5]:
ipl = pd.read_csv('ipl.csv')
ipl

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players,year
0,2008-04-18,2007/08,Bangalore,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,82,10,...,BB McCullum,J Srinath,Asad Rauf,RE Koertzen,AM Saheba,VN Kulkarni,20,"R Dravid, W Jaffer, V Kohli, JH Kallis, CL Whi...","SC Ganguly, BB McCullum, RT Ponting, DJ Hussey...",2008
1,2008-04-19,2007/08,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,207,4,...,MEK Hussey,S Venkataraghavan,MR Benson,SL Shastri,RB Tiffin,MSS Ranawat,20,"K Goel, JR Hopes, KC Sangakkara, Yuvraj Singh,...","PA Patel, ML Hayden, MEK Hussey, MS Dhoni, SK ...",2008
2,2008-04-19,2007/08,Delhi,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,132,1,...,MF Maharoof,GR Viswanath,Aleem Dar,GA Pratapkumar,IL Howell,Unknown,20,"G Gambhir, V Sehwag, S Dhawan, MK Tiwary, KD K...","T Kohli, YK Pathan, SR Watson, M Kaif, DS Lehm...",2008
3,2008-04-20,2007/08,Kolkata,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,112,5,...,DJ Hussey,FM Engineer,BF Bowden,K Hariharan,Asad Rauf,F Gomes,20,"WP Saha, BB McCullum, RT Ponting, SC Ganguly, ...","AC Gilchrist, Y Venugopal Rao, VVS Laxman, A S...",2008
4,2008-04-20,2007/08,Mumbai,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,165,7,...,MV Boucher,J Srinath,SJ Davis,DJ Harper,AV Jayaprakash,SN Bandekar,20,"L Ronchi, ST Jayasuriya, DJ Thornely, RV Uthap...","S Chanderpaul, R Dravid, LRPL Taylor, JH Kalli...",2008
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1238,2026-05-24,2026,Kolkata,"Eden Gardens, Kolkata",Delhi Capitals,Kolkata Knight Riders,Kolkata Knight Riders,field,203,5,...,Kuldeep Yadav,IR Siddiqui,K Swaroopanand,HAS Khalid,SJ Nogajski,M Krishnadas,20,"Kuldeep Yadav, Abishek Porel, KL Rahul, SU Par...","SP Narine, AM Rahane, FH Allen, MK Pandey, C G...",2026
1239,2026-05-26,2026,Dharamsala,"Himachal Pradesh Cricket Association Stadium, ...",Royal Challengers Bengaluru,Gujarat Titans,Gujarat Titans,field,254,5,...,RM Patidar,J Srinath,J Madanagopal,VK Sharma,Nitin Menon,KN Ananthapadmanabhan,20,"R Shepherd, VR Iyer, V Kohli, D Padikkal, RM P...","K Khejroliya, B Sai Sudharsan, Shubman Gill, J...",2026
1240,2026-05-27,2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...,Rajasthan Royals,Sunrisers Hyderabad,Sunrisers Hyderabad,field,243,8,...,V Suryavanshi,V Narayan Kutty,AT Holdstock,UV Gandhe,R Pandit,SJ Nogajski,20,"YBK Jaiswal, V Suryavanshi, Dhruv Jurel, R Par...","PP Hinge, Abhishek Sharma, TM Head, Ishan Kish...",2026
1241,2026-05-29,2026,New Chandigarh,Maharaja Yadavindra Singh International Cricke...,Rajasthan Royals,Gujarat Titans,Rajasthan Royals,bat,214,6,...,Shubman Gill,Prakash Bhatt,R Pandit,SJ Nogajski,AT Holdstock,UV Gandhe,20,"TU Deshpande, YBK Jaiswal, V Suryavanshi, Dhru...","Mohammed Siraj, B Sai Sudharsan, Shubman Gill,...",2026
1242,2026-05-31,2026,Ahmedabad,"Narendra Modi Stadium, Ahmedabad",Gujarat Titans,Royal Challengers Bengaluru,Royal Challengers Bengaluru,field,155,8,...,V Kohli,J Srinath,KN Ananthapadmanabhan,Nitin Menon,J Madanagopal,VK Sharma,20,"M Prasidh Krishna, B Sai Sudharsan, Shubman Gi...","JA Duffy, VR Iyer, V Kohli, D Padikkal, RM Pat...",2026

In [6]:
america = pd.read_csv(r'https://raw.githubusercontent.com/scpike/us-state-county-zip/master/geo-data.csv')
america

       state_fips    state state_abbr zipcode      county        city
0               1  Alabama         AL   35004   St. Clair       Acmar
1               1  Alabama         AL   35005   Jefferson  Adamsville
2               1  Alabama         AL   35006   Jefferson       Adger
3               1  Alabama         AL   35007      Shelby    Keystone
4               1  Alabama         AL   35010  Tallapoosa    New site
...           ...      ...        ...     ...         ...         ...
33098          56  Wyoming         WY   83126     Lincoln       Smoot
33099          56  Wyoming         WY   83127     Lincoln      Thayne
33100          56  Wyoming         WY   83128     Lincoln      Alpine
33101          56  Wyoming         WY   831HH     Lincoln  Zcta 831hh
33102          56  Wyoming         WY   831XX     Lincoln  Zcta 831xx

[33103 rows x 6 columns]

### Indexing<hr>
`syntax : variable[column_name]`

In [7]:
type(america['state_fips'])
america['state_fips'] # extract the column

0         1
1         1
2         1
3         1
4         1
         ..
33098    56
33099    56
33100    56
33101    56
33102    56
Name: state_fips, Length: 33103, dtype: int64

In [8]:
america['state'][1000]

'Arizona'

In [9]:
japan['total_births']

0       727288
1       770759
2       811622
3       840835
4       865239
        ...
117    1489816
118    1510835
119    1501591
120    1420534
121    1386981
Name: total_births, Length: 122, dtype: int64

In [70]:
student_dict = {
    'iq':[100,90,120,80,0,0,0],
    'marks':[80,70,100,50,0,0,0],
    'package':[10,7,14,2,0,0,0]
}

df1 = pd.DataFrame(student_dict)
df1.index = ['nitish','ankit','rupesh','rishabh','amit','ankita','ankita']

In [73]:
df1['iq']['ankita']

ankita    0
ankita    0
Name: iq, dtype: int64

### Fancy Indexing<hr>
`syntax : variable[ coll_of_column_names ]`

In [10]:
ipl[['date', 'winner']]
# ipl[('winner', 'team1', 'team2')] # error
ipl[['winner', 'team1', 'team2']]

,winner,team1,team2
0,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders
1,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings
2,Delhi Daredevils,Delhi Daredevils,Rajasthan Royals
3,Kolkata Knight Riders,Kolkata Knight Riders,Deccan Chargers
4,Royal Challengers Bangalore,Mumbai Indians,Royal Challengers Bangalore
...,...,...,...
1238,Delhi Capitals,Delhi Capitals,Kolkata Knight Riders
1239,Royal Challengers Bengaluru,Royal Challengers Bengaluru,Gujarat Titans
1240,Rajasthan Royals,Rajasthan Royals,Sunrisers Hyderabad
1241,Gujarat Titans,Rajasthan Royals,Gujarat Titans
1242,Royal Challengers Bengaluru,Gujarat Titans,Royal Challengers Bengaluru

### Slicing <hr>
`syntax : variable[start: end: step]`

In [25]:
ipl[0:10:1]
# ipl[0:100:6, 'dates':'venu':] #Error because of we cannot do both rows and columns 
ipl[['date', 'team1', 'team2', 'winner']][:40:]

,date,team1,team2,winner
0,2008-04-18,Royal Challengers Bangalore,Kolkata Knight Riders,Kolkata Knight Riders
1,2008-04-19,Kings XI Punjab,Chennai Super Kings,Chennai Super Kings
2,2008-04-19,Delhi Daredevils,Rajasthan Royals,Delhi Daredevils
3,2008-04-20,Kolkata Knight Riders,Deccan Chargers,Kolkata Knight Riders
4,2008-04-20,Mumbai Indians,Royal Challengers Bangalore,Royal Challengers Bangalore
5,2008-04-21,Rajasthan Royals,Kings XI Punjab,Rajasthan Royals
6,2008-04-22,Deccan Chargers,Delhi Daredevils,Delhi Daredevils
7,2008-04-23,Chennai Super Kings,Mumbai Indians,Chennai Super Kings
8,2008-04-24,Deccan Chargers,Rajasthan Royals,Rajasthan Royals
9,2008-04-25,Kings XI Punjab,Mumbai Indians,Kings XI Punjab
10,2008-04-26,Chennai Super Kings,Kolkata Knight Riders,Chennai Super Kings
11,2008-04-26,Royal Challengers Bangalore,Rajasthan Royals,Rajasthan Royals
12,2008-04-27,Kings XI Punjab,Delhi Daredevils,Kings XI Punjab
13,2008-04-27,Mumbai Indians,Deccan Chargers,Deccan Chargers
14,2008-04-28,Royal Challengers Bangalore,Chennai Super Kings,Chennai Super Kings
15,2008-04-29,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians
16,2008-04-30,Delhi Daredevils,Royal Challengers Bangalore,Delhi Daredevils
17,2008-05-01,Rajasthan Royals,Kolkata Knight Riders,Rajasthan Royals
18,2008-05-01,Deccan Chargers,Kings XI Punjab,Kings XI Punjab
19,2008-05-02,Chennai Super Kings,Delhi Daredevils,Delhi Daredevils
20,2008-05-03,Kings XI Punjab,Kolkata Knight Riders,Kings XI Punjab
21,2008-05-03,Royal Challengers Bangalore,Deccan Chargers,Royal Challengers Bangalore
22,2008-05-04,Mumbai Indians,Delhi Daredevils,Mumbai Indians
23,2008-05-04,Rajasthan Royals,Chennai Super Kings,Rajasthan Royals
24,2008-05-05,Royal Challengers Bangalore,Kings XI Punjab,Kings XI Punjab
25,2008-05-06,Chennai Super Kings,Deccan Chargers,Deccan Chargers
26,2008-05-07,Mumbai Indians,Rajasthan Royals,Mumbai Indians
27,2008-05-08,Kolkata Knight Riders,Royal Challengers Bangalore,Kolkata Knight Riders
28,2008-05-08,Delhi Daredevils,Chennai Super Kings,Chennai Super Kings
29,2008-05-09,Rajasthan Royals,Deccan Chargers,Rajasthan Royals
30,2008-05-10,Chennai Super Kings,Kings XI Punjab,Chennai Super Kings
31,2008-05-11,Deccan Chargers,Kolkata Knight Riders,Kolkata Knight Riders
32,2008-05-11,Rajasthan Royals,Delhi Daredevils,Rajasthan Royals
33,2008-05-12,Kings XI Punjab,Royal Challengers Bangalore,Kings XI Punjab
34,2008-05-13,Kolkata Knight Riders,Delhi Daredevils,Kolkata Knight Riders
35,2008-05-14,Mumbai Indians,Chennai Super Kings,Mumbai Indians
36,2008-05-15,Delhi Daredevils,Deccan Chargers,Delhi Daredevils
37,2008-05-16,Mumbai Indians,Kolkata Knight Riders,Mumbai Indians
38,2008-05-17,Delhi Daredevils,Kings XI Punjab,Kings XI Punjab
39,2008-05-17,Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals

* #### **loc** <hr>

In [38]:
america.loc[0:10:1, 'state':'zipcode':]
america.loc['state':'zipcode':] # no rows and all columns

Empty DataFrame
Columns: [state_fips, state, state_abbr, zipcode, county, city]
Index: []

In [67]:
# ipl.loc[] # error because no slicing mentioned
ipl.loc[1:10: , 'date'::]

,date,season,city,venue,team1,team2,toss_winner,toss_decision,team1_runs,team1_wickets,...,player_of_match,match_referee,umpire1,umpire2,tv_umpire,reserve_umpire,overs_limit,team1_players,team2_players,year
1,2008-04-19,2007/08,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,207,4,...,MEK Hussey,S Venkataraghavan,MR Benson,SL Shastri,RB Tiffin,MSS Ranawat,20,"K Goel, JR Hopes, KC Sangakkara, Yuvraj Singh,...","PA Patel, ML Hayden, MEK Hussey, MS Dhoni, SK ...",2008
2,2008-04-19,2007/08,Delhi,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,132,1,...,MF Maharoof,GR Viswanath,Aleem Dar,GA Pratapkumar,IL Howell,Unknown,20,"G Gambhir, V Sehwag, S Dhawan, MK Tiwary, KD K...","T Kohli, YK Pathan, SR Watson, M Kaif, DS Lehm...",2008
3,2008-04-20,2007/08,Kolkata,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,112,5,...,DJ Hussey,FM Engineer,BF Bowden,K Hariharan,Asad Rauf,F Gomes,20,"WP Saha, BB McCullum, RT Ponting, SC Ganguly, ...","AC Gilchrist, Y Venugopal Rao, VVS Laxman, A S...",2008
4,2008-04-20,2007/08,Mumbai,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,165,7,...,MV Boucher,J Srinath,SJ Davis,DJ Harper,AV Jayaprakash,SN Bandekar,20,"L Ronchi, ST Jayasuriya, DJ Thornely, RV Uthap...","S Chanderpaul, R Dravid, LRPL Taylor, JH Kalli...",2008
5,2008-04-21,2007/08,Jaipur,Sawai Mansingh Stadium,Rajasthan Royals,Kings XI Punjab,Kings XI Punjab,bat,168,4,...,SR Watson,S Venkataraghavan,Aleem Dar,RB Tiffin,I Shivram,MSS Ranawat,20,"M Kaif, Kamran Akmal, YK Pathan, SR Watson, DS...","K Goel, JR Hopes, KC Sangakkara, DPMD Jayaward...",2008
6,2008-04-22,2007/08,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Delhi Daredevils,Deccan Chargers,bat,142,8,...,V Sehwag,Talat Ali,IL Howell,AM Saheba,MR Benson,C Shamshuddin,20,"AC Gilchrist, Y Venugopal Rao, VVS Laxman, A S...","G Gambhir, V Sehwag, S Dhawan, Shoaib Malik, K...",2008
7,2008-04-23,2007/08,Chennai,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Mumbai Indians,Mumbai Indians,field,208,5,...,ML Hayden,FM Engineer,DJ Harper,GA Pratapkumar,BF Bowden,S Ravi,20,"PA Patel, ML Hayden, MEK Hussey, SK Raina, MS ...","L Ronchi, ST Jayasuriya, RV Uthappa, SM Polloc...",2008
8,2008-04-24,2007/08,Hyderabad,"Rajiv Gandhi International Stadium, Uppal",Deccan Chargers,Rajasthan Royals,Rajasthan Royals,field,214,5,...,YK Pathan,S Venkataraghavan,Asad Rauf,MR Benson,SL Shastri,C Shamshuddin,20,"AC Gilchrist, VVS Laxman, Shahid Afridi, A Sym...","Kamran Akmal, GC Smith, YK Pathan, SR Watson, ...",2008
9,2008-04-25,2007/08,Chandigarh,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Mumbai Indians,Mumbai Indians,field,182,10,...,KC Sangakkara,FM Engineer,Aleem Dar,AM Saheba,RE Koertzen,HS Sekhon,20,"K Goel, IK Pathan, KC Sangakkara, Yuvraj Singh...","L Ronchi, ST Jayasuriya, RV Uthappa, DJ Bravo,...",2008
10,2008-04-26,2007/08,Chennai,"MA Chidambaram Stadium, Chepauk",Chennai Super Kings,Kolkata Knight Riders,Kolkata Knight Riders,bat,152,1,...,JDP Oram,Talat Ali,BF Bowden,AV Jayaprakash,SJ Davis,S Ravi,20,"PA Patel, ML Hayden, MS Dhoni, MEK Hussey, S B...","SC Ganguly, BB McCullum, RT Ponting, WP Saha, ...",2008

In [51]:
df = pd.DataFrame(japan.loc[::, 'total_births'::])
df.index = japan['year']
df

,total_births,male_births,female_births,crude_birth_rate,sex_ratio_at_birth,total_fertility_rate
year,,,,,,
2023,727288,372603,354685,6.0,105.1,1.20
2022,770759,395257,375502,6.3,105.3,1.26
2021,811622,415903,395719,6.6,105.1,1.30
2020,840835,430713,410122,6.8,105.0,1.33
2019,865239,443430,421809,7.0,105.1,1.36
...,...,...,...,...,...,...
1903,1489816,763806,726010,32.7,105.2,NaN
1902,1510835,773296,737539,33.6,104.8,NaN
1901,1501591,769494,732097,33.9,105.1,NaN
1900,1420534,727916,692618,32.4,105.1,NaN
1899,1386981,713442,673539,32.0,105.9,NaN

In [58]:
df.loc[2026:2000,]
df.loc[0:10:, 'total_births':'crude_birth_rate']
df.loc[2020.3: , 'total_births':'crude_birth_rate']

      total_births  male_births  female_births  crude_birth_rate
year
2020        840835       430713         410122               6.8
2019        865239       443430         421809               7.0
2018        918400       470851         447549               7.4
2017        946146       484478         461668               7.6
2016        977242       502012         475230               7.8
...            ...          ...            ...               ...
1903       1489816       763806         726010              32.7
1902       1510835       773296         737539              33.6
1901       1501591       769494         732097              33.9
1900       1420534       727916         692618              32.4
1899       1386981       713442         673539              32.0

[119 rows x 4 columns]

In [68]:
student_dict = {
    'iq':[100,90,120,80,0,0,0],
    'marks':[80,70,100,50,0,0,0],
    'package':[10,7,14,2,0,0,0]
}

students = pd.DataFrame(student_dict)
students.index = ['nitish','ankit','rupesh','rishabh','amit','ankita','mulayam']
students

          iq  marks  package
nitish   100     80       10
ankit     90     70        7
rupesh   120    100       14
rishabh   80     50        2
amit       0      0        0
ankita     0      0        0
mulayam    0      0        0

In [ ]:
students.loc['nitish': 'ankit': , 'iq':'marks']
# students.loc[1: 10: , 'iq':'marks'] # error because index is string

         iq  marks
nitish  100     80
ankit    90     70

* #### **iloc** <hr>

In [87]:
students.iloc[0:5:1, 0:2:1]
# students.iloc[::, 'iq':'marks':] #Error because the we have used column name / label

          iq  marks
nitish   100     80
ankit     90     70
rupesh   120    100
rishabh   80     50
amit       0      0

In [90]:
df
# df.iloc[2023:1902:-1 ] # we get empty coz we are using label
df.iloc[0:10:1]

,total_births,male_births,female_births,crude_birth_rate,sex_ratio_at_birth,total_fertility_rate
year,,,,,,
2023,727288,372603,354685,6.0,105.1,1.20
2022,770759,395257,375502,6.3,105.3,1.26
2021,811622,415903,395719,6.6,105.1,1.30
2020,840835,430713,410122,6.8,105.0,1.33
2019,865239,443430,421809,7.0,105.1,1.36
2018,918400,470851,447549,7.4,105.2,1.42
2017,946146,484478,461668,7.6,104.9,1.43
2016,977242,502012,475230,7.8,105.6,1.44
2015,1005721,515468,490253,8.0,105.1,1.45
2014,1003609,515572,488037,8.0,105.6,1.42