In [1]:
import numpy as np
import pandas as pd

In [13]:
covid = pd.read_csv('country_wise_latest.csv')
covid['Country/Region'].is_unique #True
covid.head(2)

,Country/Region,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
0,Afghanistan,36263,1269,25198,9796,106,10,18,3.50,69.49,5.04,35526,737,2.07,Eastern Mediterranean
1,Albania,4880,144,2745,1991,117,6,63,2.95,56.25,5.25,4171,709,17.00,Europe

In [33]:
gone_case = pd.read_csv('addiction_population_data.csv')
gone_case.info()

<class 'pandas.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 25 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   id                         3000 non-null   int64
 1   name                       3000 non-null   str
 2   age                        3000 non-null   int64
 3   gender                     3000 non-null   str
 4   country                    3000 non-null   str
 5   city                       3000 non-null   str
 6   education_level            2580 non-null   str
 7   employment_status          3000 non-null   str
 8   annual_income_usd          3000 non-null   int64
 9   marital_status             3000 non-null   str
 10  children_count             3000 non-null   int64
 11  smokes_per_day             3000 non-null   int64
 12  drinks_per_week            3000 non-null   int64
 13  age_started_smoking        3000 non-null   int64
 14  age_started_drinking       3000 non-null   int64
 15  attempts_to_quit_smoking   3000 non-null   int64
 16  attempts_to_quit_drinking  3000 non-null   int64
 17  has_health_issues          3000 non-null   bool
 18  mental_health_status       3000 non-null   str
 19  exercise_frequency         3000 non-null   str
 20  diet_quality               3000 non-null   str
 21  sleep_hours                3000 non-null   float64
 22  bmi                        3000 non-null   float64
 23  social_support             2247 non-null   str
 24  therapy_history            1986 non-null   str
dtypes: bool(1), float64(2), int64(10), str(12)
memory usage: 565.6 KB

## Boolean Filtering <hr>
`syntax : variable[ condtion ]`

In [ ]:
covid[covid['Country/Region'] == 'India']

# covid[covid['Country/Region']] # error coz no condtion  and it is a syntax of indexing

covid[covid['Deaths'] > 33000]

covid[(covid['Deaths'] > 10000) & (covid['New deaths'] > 20)]

covid[(covid['New cases'] > 1000) & (covid['Deaths'] > 10000) ]['Country/Region']

23     Brazil
61     France
79      India
81       Iran
111    Mexico
132      Peru
138    Russia
173        US
Name: Country/Region, dtype: str

In [49]:
gone_case[gone_case['smokes_per_day'] > 18 ]

gone_case[(gone_case['smokes_per_day'] > 15) & (gone_case['gender'] == 'Male' ) ]

gone_case[(gone_case['smokes_per_day'] > 15) & (gone_case['gender'] == 'Male' ) ]['id'].count()

gone_case[(gone_case['smokes_per_day'] > 15) & (gone_case['gender'] == 'Female')]['id'].count()

# gone_case[(covid['Deaths'] > 15) & (gone_case['gender'] == 'Female')]['id'] # works but not prefered

# gone_case[ np.int32(10) ]  # this is indexing

np.int64(62)

## Modification <hr>

#### modification of specific values

In [52]:
gone_case['name'][1] = 'Jay'

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_7236\4262450427.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  gone_case['name'][1] = 'Jay'

In [ ]:
gone_case.loc[::, 'name' ][1] = 'Jay'
gone_case

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_7236\3281246888.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  gone_case.loc[::, 'name' ][1] = 'Jay'

,id,name,age,gender,country,city,education_level,employment_status,annual_income_usd,marital_status,...,attempts_to_quit_smoking,attempts_to_quit_drinking,has_health_issues,mental_health_status,exercise_frequency,diet_quality,sleep_hours,bmi,social_support,therapy_history
0,1,Michael Bates,66,Other,Yemen,Martinmouth,Secondary,Student,45595,Married,...,6,2,True,Good,Daily,Average,5.6,22.4,NaN,Current
1,2,Brian Thompson,29,Male,Saudi Arabia,Harperhaven,Primary,Self-Employed,145842,Single,...,1,6,False,Poor,Weekly,Good,6.7,24.1,Moderate,NaN
2,3,Steven Little,75,Male,Togo,Chanport,Postgraduate,Unemployed,162480,Single,...,9,9,True,Good,Never,Good,6.2,22.2,Weak,NaN
3,4,Michael Mathews,35,Other,Togo,North Cory,University,Unemployed,16023,In a relationship,...,5,7,False,Average,Daily,Good,7.2,25.5,Moderate,Current
4,5,Nicholas Sanchez,38,Female,Morocco,Danielberg,College,Self-Employed,62933,In a relationship,...,4,7,True,Poor,Weekly,Good,8.5,31.2,Weak,Past
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,Mary Bartlett,29,Other,Macedonia,Port Kimberly,Postgraduate,Employed,118269,Single,...,9,1,True,Poor,Never,Average,6.6,27.4,Moderate,Current
2996,2997,Beth Sanchez,51,Male,Saudi Arabia,Smithbury,College,Employed,35898,Widowed,...,9,2,True,Poor,Rarely,Good,4.3,27.7,Moderate,Past
2997,2998,Megan Duffy,15,Male,Falkland Islands (Malvinas),Clinebury,College,Retired,167501,Widowed,...,1,8,True,Poor,Rarely,Poor,6.6,23.5,Moderate,Past
2998,2999,Jeffery Lawson,38,Male,Bermuda,Colleenport,Secondary,Retired,135893,Married,...,9,3,False,Poor,Rarely,Poor,4.9,27.2,NaN,Current
2999,3000,Kathryn Gray,41,Other,Jamaica,Turnertown,NaN,Employed,124049,Single,...,3,5,False,Good,Daily,Average,5.2,19.6,Moderate,Past

In [64]:
gone_case['age'][0] = 30 # specific modicatio will give warning

C:\Users\LENOVO\AppData\Local\Temp\ipykernel_7236\2127119307.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment.
Such chained assignment never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

Try using '.loc[row_indexer, col_indexer] = value' instead, to perform the assignment in a single step.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html#chained-assignment
  gone_case['age'][0] = 30 # specific modicatio will give warning

In [63]:
gone_case['age'] = 30
gone_case

,id,name,age,gender,country,city,education_level,employment_status,annual_income_usd,marital_status,...,attempts_to_quit_smoking,attempts_to_quit_drinking,has_health_issues,mental_health_status,exercise_frequency,diet_quality,sleep_hours,bmi,social_support,therapy_history
0,1,Michael Bates,30,Other,Yemen,Martinmouth,Secondary,Student,45595,Married,...,6,2,True,Good,Daily,Average,5.6,22.4,NaN,Current
1,2,Brian Thompson,30,Male,Saudi Arabia,Harperhaven,Primary,Self-Employed,145842,Single,...,1,6,False,Poor,Weekly,Good,6.7,24.1,Moderate,NaN
2,3,Steven Little,30,Male,Togo,Chanport,Postgraduate,Unemployed,162480,Single,...,9,9,True,Good,Never,Good,6.2,22.2,Weak,NaN
3,4,Michael Mathews,30,Other,Togo,North Cory,University,Unemployed,16023,In a relationship,...,5,7,False,Average,Daily,Good,7.2,25.5,Moderate,Current
4,5,Nicholas Sanchez,30,Female,Morocco,Danielberg,College,Self-Employed,62933,In a relationship,...,4,7,True,Poor,Weekly,Good,8.5,31.2,Weak,Past
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,Mary Bartlett,30,Other,Macedonia,Port Kimberly,Postgraduate,Employed,118269,Single,...,9,1,True,Poor,Never,Average,6.6,27.4,Moderate,Current
2996,2997,Beth Sanchez,30,Male,Saudi Arabia,Smithbury,College,Employed,35898,Widowed,...,9,2,True,Poor,Rarely,Good,4.3,27.7,Moderate,Past
2997,2998,Megan Duffy,30,Male,Falkland Islands (Malvinas),Clinebury,College,Retired,167501,Widowed,...,1,8,True,Poor,Rarely,Poor,6.6,23.5,Moderate,Past
2998,2999,Jeffery Lawson,30,Male,Bermuda,Colleenport,Secondary,Retired,135893,Married,...,9,3,False,Poor,Rarely,Poor,4.9,27.2,NaN,Current
2999,3000,Kathryn Gray,30,Other,Jamaica,Turnertown,NaN,Employed,124049,Single,...,3,5,False,Good,Daily,Average,5.2,19.6,Moderate,Past

In [72]:
gone_case.iloc[0:10:, 3:4:] = 'Female'

In [73]:
gone_case

,id,name,age,gender,country,city,education_level,employment_status,annual_income_usd,marital_status,...,attempts_to_quit_smoking,attempts_to_quit_drinking,has_health_issues,mental_health_status,exercise_frequency,diet_quality,sleep_hours,bmi,social_support,therapy_history
0,1,Michael Bates,30,Female,Yemen,Martinmouth,Secondary,Student,45595,Married,...,6,2,True,Good,Daily,Average,5.6,22.4,NaN,Current
1,2,Brian Thompson,30,Female,Saudi Arabia,Harperhaven,Primary,Self-Employed,145842,Single,...,1,6,False,Poor,Weekly,Good,6.7,24.1,Moderate,NaN
2,3,Steven Little,30,Female,Togo,Chanport,Postgraduate,Unemployed,162480,Single,...,9,9,True,Good,Never,Good,6.2,22.2,Weak,NaN
3,4,Michael Mathews,30,Female,Togo,North Cory,University,Unemployed,16023,In a relationship,...,5,7,False,Average,Daily,Good,7.2,25.5,Moderate,Current
4,5,Nicholas Sanchez,30,Female,Morocco,Danielberg,College,Self-Employed,62933,In a relationship,...,4,7,True,Poor,Weekly,Good,8.5,31.2,Weak,Past
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,2996,Mary Bartlett,30,Other,Macedonia,Port Kimberly,Postgraduate,Employed,118269,Single,...,9,1,True,Poor,Never,Average,6.6,27.4,Moderate,Current
2996,2997,Beth Sanchez,30,Male,Saudi Arabia,Smithbury,College,Employed,35898,Widowed,...,9,2,True,Poor,Rarely,Good,4.3,27.7,Moderate,Past
2997,2998,Megan Duffy,30,Male,Falkland Islands (Malvinas),Clinebury,College,Retired,167501,Widowed,...,1,8,True,Poor,Rarely,Poor,6.6,23.5,Moderate,Past
2998,2999,Jeffery Lawson,30,Male,Bermuda,Colleenport,Secondary,Retired,135893,Married,...,9,3,False,Poor,Rarely,Poor,4.9,27.2,NaN,Current
2999,3000,Kathryn Gray,30,Other,Jamaica,Turnertown,NaN,Employed,124049,Single,...,3,5,False,Good,Daily,Average,5.2,19.6,Moderate,Past

In [83]:
# covid.set_index('Country/Region', inplace=True)
covid.loc['China':'China':, 'Confirmed'] = 100000000
covid.loc['China':]

,Confirmed,Deaths,Recovered,Active,New cases,New deaths,New recovered,Deaths / 100 Cases,Recovered / 100 Cases,Deaths / 100 Recovered,Confirmed last week,1 week change,1 week % increase,WHO Region
Country/Region,,,,,,,,,,,,,,
China,100000000,4656,78869,3258,213,4,7,5.37,90.88,5.90,85622,1161,1.36,Western Pacific
Colombia,257101,8777,131161,117163,16306,508,11494,3.41,51.02,6.69,204005,53096,26.03,Americas
Comoros,354,7,328,19,0,0,0,1.98,92.66,2.13,334,20,5.99,Africa
Congo (Brazzaville),3200,54,829,2317,162,3,73,1.69,25.91,6.51,2851,349,12.24,Africa
Congo (Kinshasa),8844,208,5700,2936,13,4,190,2.35,64.45,3.65,8443,401,4.75,Africa
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
West Bank and Gaza,10621,78,3752,6791,152,2,0,0.73,35.33,2.08,8916,1705,19.12,Eastern Mediterranean
Western Sahara,10,1,8,1,0,0,0,10.00,80.00,12.50,10,0,0.00,Africa
Yemen,1691,483,833,375,10,4,36,28.56,49.26,57.98,1619,72,4.45,Eastern Mediterranean
Zambia,4552,140,2815,1597,71,1,465,3.08,61.84,4.97,3326,1226,36.86,Africa
Zimbabwe,2704,36,542,2126,192,2,24,1.33,20.04,6.64,1713,991,57.85,Africa